name: deploy
on: workflow_dispatch:
jobs:
deploy:
name: Deploy to AWS
runs-on: ubuntu-22.04
steps:
name: Deploy
uses: appleboy/ssh-action@v0.1.8
with:
host: 54.86.23.146
port: 22
username: campus-a-plus
key: ${{secrets.PRIVATE_KEY}}
script: "cd www; git pull origin main"
